version: '3.0'

services:
   redis:
     image: redis
     networks:
       - webnet
   db:
     image: mdillon/postgis
     volumes:
       - ./pgdata:/var/lib/postgresql/data
     restart: always
     networks:
       - webnet
     ports:
       - "1111:5432"
     environment:
       POSTGRES_USER: geodev
       POSTGRES_PASSWORD: dev
       POSTGRES_DB: geodev
   web:
     build: .
     ports:
       - "5555:5555"
#     links:
#      - "db:database"
     networks:
       - webnet
     depends_on:
       - db
       - redis
     # command: ["./wait-for-postgres.sh", "db:1111", "cd /app && go run *.go -h db -dbp 1111"]

     #command: ["./app/wait-for-postgres.sh", "db:5432", "git clone https://github.com/sjsafranek/mvt-server.git && cd mvt-server && go run *.go -h db -dbp 1111"]
   # web:
   #   build: .
   #   ports:
   #     - "5555:5555"
   #   networks:
   #     - webnet
   #   depends_on:
   #     - db
   #     - redis
networks:
   webnet:
