title = "MVT-Server"

[cache]
  type = "redis"
  port = 6379

[database]
  database = "geodev"
  host = "127.0.0.1"
  port = 5432
  password = "dev"
  type = "postgres"
  username = "geodev"

[server]
  port = 5555
  secret = "8XsiSYmH3j"
